apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    move2kube.konveyor.io/service: ts-user-mongo
  name: ts-user-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      move2kube.konveyor.io/service: ts-user-mongo
  template:
    metadata:
      labels:
        move2kube.konveyor.io/service: ts-user-mongo
      name: ts-user-mongo
    spec:
      containers:
        - name: ts-user-mongo
          image: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              protocol: TCP
      restartPolicy: Always
