apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    move2kube.konveyor.io/service: ts-voucher-mysql
  name: ts-voucher-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      move2kube.konveyor.io/service: ts-voucher-mysql
  template:
    metadata:
      labels:
        move2kube.konveyor.io/service: ts-voucher-mysql
      name: ts-voucher-mysql
    spec:
      containers:
        - name: ts-voucher-mysql
          image: mysql
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
      restartPolicy: Always
